# Generated by Django 4.1.7 on 2023-03-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_imagemodel_remove_message_image_message_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
    ]
